### ISSUE TITLE
Server crashes after a while when using cross-domain

### ISSUE THREAD

**Issue by xMartin** [hoodiehq/hoodie-server#329] opened 2014-11-05 10:35 UTC
Running Hoodie with server 2.0.0 the process crashes after a while with the following error. This only happens when using it with CORS, client being served on another domain than server.

	Debug: hapi, internal, implementation, error 
		TypeError: Cannot call method 'code' of undefined
		at internals.addCorsAndBearerToken (.../hoodie/node_modules/hoodie-server/lib/server/plugins/api/index.js:32:18)
		at .../hoodie/node_modules/hoodie-server/node_modules/hapi/node_modules/h2o2/lib/index.js:139:52
		at finish (.../hoodie/node_modules/hoodie-server/node_modules/wreck/lib/index.js:92:20)
		at wrapped (.../hoodie/node_modules/hoodie-server/node_modules/wreck/node_modules/hoek/lib/index.js:771:20)
		at ClientRequest.onError (.../hoodie/node_modules/hoodie-server/node_modules/wreck/lib/index.js:101:16)
		at ClientRequest.g (events.js:180:16)
		at ClientRequest.emit (events.js:117:20)
		at Socket.socketErrorListener (http.js:1551:9)
		at Socket.emit (events.js:95:17)
		at net.js:440:14

**Comment by inator** [comment] 2015-01-06 13:39
We're continuing to see this with the newer versions of Hoodie as well.  I believe this issue is the same or related to issue #280.

**Comment by inator** [comment] 2015-01-06 14:18
"this usually means that the couch process died."

@svnlto - I made a similar observation just this morning, when I noticed that the www front end was working, but none of the other endpoints were accessible.  It appears that CouchDB falls right from under Hoodie when running server version 2.0.0, but his absolutely does not happen on server version 1.2.4.  We've had instances with significant traffic running various CORS configurations on the older version with stellar stability.  Something significantly changed since then, and although it seems to have gotten better as the server has gone through revision, it is clearly still there.

This is a real problem, and I'm prepared to work directly with you and anyone else that is willing to help nail this down.  I can commit some VMs if needed too.  Please advise.

**Comment by svnlto** [comment] 2015-01-06 14:25
First steps should be, track down the version which the issue has been introduced in.

**Comment by inator** [comment] 2015-01-06 14:59
@svnlto - Every version since server 1.2.4 has exhibited this problem as far as I can tell in my testing.  I have yet to see any version but that stay up for any long length of time.

**Comment by inator** [comment] 2015-01-06 15:10
@svnlto - Do you think there could be a compatibility issue with CouchDB at a certain version level?  We run 1.5.0, and I think Nodejitsu/IrisCouch does as well.  I'm curious what version are being used on installs that are deemed stable with the newer versions (i.e. minutes.io - @janl , @gr2m ?).

**Comment by janl** [comment] 2015-01-06 15:39
This is unlikely to be a CouchDB compat issue. My current suspect is the bearer token code/patch. If we can get a test case going, it shouldn’t be too hard to patch.

**Comment by janl** [comment] 2015-01-08 22:07
There are multiple things being reported here, e.g. #280 must be a different thing from what @xMartin reports as we get an OOM situation there and this is a clean error message.

Then there is the dying CouchDB issue which is also unrelated.

Do we have a reproducible test case that reproduces the original error message ` TypeError: Cannot call method 'code' of undefined`?

**Comment by chetstone** [comment] 2015-01-17 05:10
I'm pretty sure this is the error I got when I simply set up an account on nodejitsu and followed the steps on the wiki to install 'my-first-hoodie' on nodejitsu. 


It was definitely a 'hapi' error.
--

May all beings be happy!

**Comment by ransomw** [comment] 2015-11-22 08:10
i got something similar...

after restarting the hoodie server, reloading a page (such that the browser's `localStorage` has a logged-in state), and attempting to log-out i got the following error

```
Debug: internal, implementation, error
    TypeError: Property 'code' of object Error: Client request error: write EPIPE is not a function
    at module.exports.addCorsAndBearerToken (/home/ransom/cljs-todos/hoodie_app/node_modules/hoodie-server/lib/server/hapi_plugins/api/internals.js:10:18)
    at /home/ransom/cljs-todos/hoodie_app/node_modules/hoodie-server/node_modules/hapi/node_modules/h2o2/lib/index.js:146:52
    at finish (/home/ransom/cljs-todos/hoodie_app/node_modules/hoodie-server/node_modules/hapi/node_modules/h2o2/node_modules/wreck/lib/index.js:137:20)
    at wrapped (/home/ransom/cljs-todos/hoodie_app/node_modules/hoodie-server/node_modules/hapi/node_modules/hoek/lib/index.js:858:20)
    at ClientRequest.onError (/home/ransom/cljs-todos/hoodie_app/node_modules/hoodie-server/node_modules/hapi/node_modules/h2o2/node_modules/wreck/lib/index.js:146:16)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:117:20)
    at Socket.socketErrorListener (http.js:1551:9)
    at Socket.emit (events.js:95:17)
    at onwriteError (_stream_writable.js:238:10)
```

the server didn't crash, and a second login attempt returned a 401 rather than a 5xx error, so my application could reauthenticate, login, and successfully log out.

seems like a minor issue.  i only am posting since the error message is labeled "implementation error."

this is hoodie-server 4.0.3

**Comment by gr2m** [comment] 2015-11-23 05:01
Thanks for reporting the issue Ransom! I'll have a look at it the next week. Monday & Tuesday are packed, but I hope to have time to have a look on Wednesday. Unless someone else is faster than me :)

**Comment by boennemann** [comment] 2015-11-26 17:22
The code that was probably causing this is pretty much 100% gone with the hoodie-server rewrite. I'm closing this for now, and we can reopen as soon as we're having the same problem again.

**Closed by boennemann** 2015-11-26 17:22 UTC
