### ISSUE TITLE
create custom views / updates for /_users

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-server#208] opened 2014-01-24 09:38 UTC
this keeps sticking in my mind, gotta write it down finally.

* signup
* change username
* change password
* get / set user data* (the part that the user can change, like name ...)
* get account data* (the part, that the user cannot change, like account plan, timestamps, etc)

This would remove complexity from client code, plus it would make it less likely that code needs to be adjusted when internal formats / namings change in /_users docs.

**Comment by svnlto** [comment] 2015-01-07 12:45
I'm currently trying to figure out what goes into hoodie-server 2.0
Would this issue still be relevant?

**Comment by gr2m** [comment] 2015-01-07 12:53
Yes, it'd be great. Maybe we can make it together with https://github.com/hoodiehq/hoodie-server/issues/319?

**Comment by svnlto** [comment] 2015-01-07 12:54
@gr2m can you update #319 and close this one then?

**Comment by gr2m** [comment] 2015-01-07 12:55
@svnlto will do, thanks

**Comment by boennemann** [comment] 2015-08-15 04:19
duplicate of #319

**Closed by boennemann** 2015-08-15 04:19 UTC
Labels: enhancement, release-1.0.0
