### ISSUE TITLE
Plug in event not getting called. 

### ISSUE THREAD

**Issue by simonv3** [hoodiehq/hoodie-server#374] opened 2015-08-16 02:43 UTC
I've been trying out the new way to run hoodie and ran into an issue with calling plugin functions.

The plugin is this one: 

https://github.com/simonv3/hoodie-plugin-isbn

It's fairly simple. On receiving input it queries an external API based on an auth key set through the admin dashboard. (Another issue is that with the most recent issue of hoodie-server I can't access the admin dashboard anymore, I'll open an other issue for that). 

When stripped to its most bare minimum: 

hoodie.isbn.js:

```javascript
Hoodie.extend(function(hoodie) {
  hoodie.isbn = {};
  hoodie.isbn.searchbooks = hoodie.task('searchbooks').start;
});
```

worker.js
```javascript
module.exports = function(hoodie, doneCallback) {
  hoodie.task.on('searchbooks:add', searchBooks);
  function searchBooks(dbName, search) {
    console.log('Going on a search for %s', search.query);
  }
  doneCallback();
};
```

and where it gets called from within the code:
```javascript
hoodie.isbn.searchbooks({
        query: searchQuery
});
```

Here are the logs for starting up the app:

```
🐶 Hoodie Verb💬  app Initializing
🐶 Hoodie Warn⚡️  config No App port specified. Will be available at 127.0.0.1:6020
🐶 Hoodie Warn⚡️  config No Admin port specified. Will be available at 127.0.0.1:6021
🐶 Hoodie Warn⚡️  config No database port specified. Will be available at 127.0.0.1:6022
🐶 Hoodie Verb💬  hapi Will show http and log output
🐶 Hoodie Info🔍  database PouchDB Server started
🐶 Hoodie Sill📣  database Checking for admin party mode
🐶 Hoodie Sill📣  database Not in admin party mode
🐶 Hoodie Sill📣  database Checking if provided credentials work
🐶 Hoodie Verb💬  database Provided credentials work
🐶 Hoodie Sill📣  database Creating "app"
🐶 Hoodie Info🔍  database Created "app"
🐶 Hoodie Verb💬  database Creating appconfig document in plugins database
🐶 Hoodie Sill📣  database Creating "plugins"
🐶 Hoodie Info🔍  database Created "plugins"
🐶 Hoodie Verb💬  database Setting Hoodie-specific config
🐶 Hoodie Sill📣  database Saving config
🐶 Hoodie Sill📣  plugins Reading project's package.json for plugins
🐶 Hoodie Verb💬  hooks Running static hook server.pack.pre
🐶 Hoodie Sill📣  hapi Registering internal plugins
🐶 Hoodie Verb💬  hapi Registerd internal plugins
🐶 Hoodie Verb💬  hooks Running static hook server.pack.post
🐶 Hoodie Verb💬  plugins Starting all plugins
🐶 Hoodie Info🔍  database Using legacy changes feed pooling (CouchDB < 1.4, PouchDB Server)
🐶 Hoodie Info🔍  plugins Starting plugin hoodie-plugin-appconfig
🐶 Hoodie Sill📣  plugins No worker found at /Users/simon/src/reading-list-hoodie/read/node_modules/@hoodie/dev-top-level/node_modules/hoodie-plugin-appconfig
🐶 Hoodie Info🔍  plugins Starting plugin hoodie-plugin-email
🐶 Hoodie Sill📣  plugins Worker found at /Users/simon/src/reading-list-hoodie/read/node_modules/@hoodie/dev-top-level/node_modules/hoodie-plugin-email
🐶 Hoodie Info🔍  plugins Starting plugin hoodie-plugin-users
🐶 Hoodie Sill📣  plugins Worker found at /Users/simon/src/reading-list-hoodie/read/node_modules/@hoodie/dev-top-level/node_modules/hoodie-plugin-users
🐶 Hoodie Info🔍  plugins Starting plugin hoodie-plugin-backbone
🐶 Hoodie Sill📣  plugins No worker found at /Users/simon/src/reading-list-hoodie/read/node_modules/hoodie-plugin-backbone
🐶 Hoodie Info🔍  plugins Starting plugin hoodie-plugin-isbn
🐶 Hoodie Sill📣  plugins Worker found at /Users/simon/src/reading-list-hoodie/read/node_modules/hoodie-plugin-isbn
🐶 Hoodie Sill📣  plugins No hook found at /Users/simon/src/reading-list-hoodie/read/node_modules/@hoodie/dev-top-level/node_modules/hoodie-plugin-appconfig/hooks/dynamic.js
🐶 Hoodie Sill📣  plugins No hook found at /Users/simon/src/reading-list-hoodie/read/node_modules/@hoodie/dev-top-level/node_modules/hoodie-plugin-email/hooks/dynamic.js
🐶 Hoodie Sill📣  plugins No hook found at /Users/simon/src/reading-list-hoodie/read/node_modules/hoodie-plugin-backbone/hooks/dynamic.js
🐶 Hoodie Sill📣  plugins No hook found at /Users/simon/src/reading-list-hoodie/read/node_modules/hoodie-plugin-isbn/hooks/dynamic.js
🐶 Hoodie Sill📣  plugins Hook found at /Users/simon/src/reading-list-hoodie/read/node_modules/@hoodie/dev-top-level/node_modules/hoodie-plugin-users/hooks/dynamic.js
🐶 Hoodie Info🔍  plugins All plugins started
🐶 Hoodie Verb💬  app Starting
🐶 Your Hoodie app has started on http://127.0.0.1:6020
```

**Comment by gr2m** [comment] 2015-08-16 22:26
@boennemann that part looks odd to me:

> 🐶 Hoodie Info🔍  database Using legacy changes feed pooling (CouchDB < 1.4, PouchDB Server)

Especially as it also says `database PouchDB Server started` above.

**Comment by boennemann** [comment] 2015-08-16 23:53
@gr2m No that's totally fine. (see info loglevel). I've chatted with Simon via Slack and I already have a rough idea of what the problem is.




Will investigate/document more tomorrow :)

**Comment by boennemann** [comment] 2015-08-21 18:40
Sorry for the delayed update: This one should've fixed it https://github.com/hoodiehq/hoodie-server/commit/c69dba3a5b5513eccef5de7eda056a7d2909c289

I'm closing this now, but if you can't confirm we'll reopen it right away.

Best,
Stephan

**Closed by boennemann** 2015-08-21 18:40 UTC

**Comment by simonv3** [comment] 2015-08-21 23:56
I just had a go at updating to hoodie-server 9.3.1, but it looks like the plugin still doesn't get called. Same code I mentioned above.

logs: http://pastebin.com/RBjtkAfn

Unrelated, but maybe related, I thought I should mention it: I can't log in to the admin dashboard anymore with the admin password I had set up. It lets me sign in and shows the dashboard, but immediately an alert pops up with `HoodieUnauthorizedError: You are not authorized to access this db.`. I can click okay, and I don't get signed out, but when I try to change any values and save, I get the same error message in the form.
